name: Build, Test , Deploy School

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build Frontend and Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install and Build Frontend
        run: |
          cd frontend
          npm insatll
          npm run dev

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Upload Build Articraft
        uses: actions/upload-artifact@v4
        with:
          name: build_output
        path: |
          frontend/dist
          backend
